import './style.css';

// แก้ไขชื่อคอร์ส ราคา และ prompt ภาพได้ที่นี่
const COURSES = [
  { id:'creative', tag:'CREATIVE', title:'Content Creator Blueprint', desc:'เปลี่ยนไอเดียให้เป็นคอนเทนต์ที่คนอยากหยุดดู', price:1290, oldPrice:1890, lessons:8, duration:'6 ชม. 20 นาที', color:'#d7ff3f', prompt:'minimal cinematic editorial photo of a Thai content creator desk, camera, notebook, warm sunlight, high end magazine aesthetic, no text' },
  { id:'design', tag:'DESIGN', title:'Design That Converts', desc:'ออกแบบหน้าเว็บที่สวย มีเหตุผล และพาคนไปถึงปุ่มซื้อ', price:1490, oldPrice:2190, lessons:10, duration:'8 ชม. 10 นาที', color:'#a9c7ff', prompt:'luxury web design workspace, typography poster, abstract glass shapes, editorial studio lighting, no words' },
  { id:'business', tag:'BUSINESS', title:'Freelance to Freedom', desc:'สร้างระบบรับงาน ตั้งราคา และเติบโตแบบไม่หมดไฟ', price:990, oldPrice:1490, lessons:7, duration:'5 ชม. 45 นาที', color:'#ffb49a', prompt:'calm independent freelancer working at a sunlit cafe, notebook and laptop, natural candid editorial photography, no text' },
];

const BANK = { bank:'กสิกรไทย (KBank)', account:'102-827-0727', name:'สรวิชญ์ น้อยวิมล' };
const discount = 200;
const endAt = Number(localStorage.getItem('skillrise-offer-end')) || (Date.now() + 86400000);
localStorage.setItem('skillrise-offer-end', endAt);
const completed = JSON.parse(localStorage.getItem('skillrise-completed') || '{}');

const money = n => new Intl.NumberFormat('th-TH').format(n);
const course = id => COURSES.find(c => c.id === id) || COURSES[0];
const imageUrl = prompt => `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt)}?width=1200&height=900&nologo=true&seed=${prompt.length}`;
const icon = (name) => ({arrow:'↗', play:'▶', lock:'⌁', check:'✓', close:'×', menu:'☰'}[name] || '•');

function header(){ return `<header><a class="brand" href="#/">SKILL<span>RISE</span><i></i></a><nav><a href="#/courses">คอร์สเรียน</a><a href="#/about">เกี่ยวกับเรา</a><a href="#/courses" class="nav-cta">เริ่มเรียน <span>↗</span></a></nav><button class="mobile-menu" aria-label="เมนู">${icon('menu')}</button></header>` }
function visual(c, cls=''){ return `<div class="course-visual ${cls}" style="--accent:${c.color}"><img src="${imageUrl(c.prompt)}" alt="ภาพประกอบคอร์ส ${c.title}" loading="lazy" onerror="this.style.display='none'"/><div class="visual-noise"></div><p>GENERATED<br>FOR THIS COURSE</p></div>` }
function card(c){return `<article class="course-card reveal"><a href="#/course/${c.id}">${visual(c)}<div class="card-body"><div class="eyebrow">${c.tag} <span>${c.lessons} บทเรียน</span></div><h3>${c.title}</h3><p>${c.desc}</p><div class="card-bottom"><b>฿${money(c.price)}</b><span class="round-arrow">${icon('arrow')}</span></div></div></a></article>`}
function home(){return `${header()}<main>
<section class="hero"><div class="hero-copy reveal"><div class="pill"><span></span> เปิดรับรุ่นใหม่ วันนี้</div><h1>เรียนให้เป็น<br><em>ตัวคุณ</em>ในเวอร์ชัน<br>ที่ไปได้ไกลกว่า</h1><p>คอร์สออนไลน์สำหรับคนที่อยากเปลี่ยนทักษะ<br>ให้กลายเป็นผลงานและโอกาสจริง</p><div class="hero-actions"><a class="button primary" href="#/courses">ดูคอร์สทั้งหมด <b>↗</b></a><a class="text-link" href="#/about">เราเชื่อเรื่องอะไร <span>↓</span></a></div></div>
<div class="hero-art reveal">${visual(COURSES[0], 'hero-image')}<div class="float-note top">01 <span>เรียนจาก<br>ประสบการณ์จริง</span></div><div class="float-note bottom"><strong>4.9</strong><span>คะแนนเฉลี่ย<br>จากผู้เรียน</span></div></div><div class="hero-index">SCROLL TO EXPLORE <span></span> 01—04</div></section>
<section class="intro section"><div class="section-number">( 01 )</div><div class="intro-copy reveal"><p class="kicker">LEARN WITH INTENTION</p><h2>ไม่ใช่แค่ดูจบ<br>แต่ <em>ทำได้จริง</em></h2></div><div class="intro-text reveal"><p>เราออกแบบทุกบทเรียนให้สั้น ชัด และพาไปลงมือทำทันที พร้อมลำดับการเรียนที่ทำให้คุณไม่หลงทาง</p><a class="text-link" href="#/courses">ดูรูปแบบการเรียน <span>↗</span></a></div></section>
<section class="courses-preview section"><div class="section-head"><div><p class="kicker">EXPLORE COURSES</p><h2>เลือกเส้นทาง<br>ที่อยากไปต่อ</h2></div><a class="button outline" href="#/courses">คอร์สทั้งหมด <b>↗</b></a></div><div class="course-grid">${COURSES.map(card).join('')}</div></section>
<section class="statement"><div class="reveal"><p class="kicker">A DIFFERENT WAY TO LEARN</p><h2>คุณไม่ต้อง<br>พร้อมทั้งหมด<br><em>เพื่อเริ่มต้น</em></h2><a class="button lime" href="#/courses">เริ่มต้นวันนี้ <b>↗</b></a></div><div class="statement-side reveal"><p>แค่เริ่มจากบทเรียนเดียว<br>แล้วให้ความสม่ำเสมอพาคุณไป</p><span>SKILLRISE<br>— 2026</span></div></section>
</main>${footer()}`}
function courses(){return `${header()}<main class="page"><section class="page-title reveal"><p class="kicker">ALL COURSES / 03</p><h1>หาทักษะที่<br><em>ใช่สำหรับคุณ</em></h1><p>ทุกคอร์สเรียนได้ตลอดชีพ อัปเดตบทเรียนใหม่ให้โดยไม่มีค่าใช้จ่ายเพิ่ม</p></section><section class="catalog">${COURSES.map((c,i)=>`<article class="catalog-item reveal"><div class="catalog-no">0${i+1}</div>${visual(c)}<div class="catalog-detail"><p class="eyebrow">${c.tag} <span>${c.duration}</span></p><h2>${c.title}</h2><p>${c.desc}</p><div><b>฿${money(c.price)}</b> <del>฿${money(c.oldPrice)}</del></div></div><a class="circle-button" href="#/course/${c.id}">↗</a></article>`).join('')}</section></main>${footer()}`}
function coursePage(id){const c=course(id); const done=completed[c.id]||0; const lessons=Array.from({length:c.lessons},(_,i)=>({title:['เริ่มต้น: เป้าหมายของคุณ','พื้นฐานที่ต้องรู้','วางระบบให้ทำตามได้','ลงมือทำ: Workshop','วิธีคิดแบบมืออาชีพ','แก้ปัญหาที่พบบ่อย','โปรเจกต์ของคุณ','สรุปและก้าวต่อไป'][i]||`บทเรียนเพิ่มเติม ${i+1}`, duration:['08:42','14:20','21:05','18:12','12:48','16:30','24:15','09:10'][i]||'12:00'})); return `${header()}<main class="course-page"><section class="course-hero"><div class="reveal"><a class="back" href="#/courses">← คอร์สทั้งหมด</a><p class="kicker">${c.tag} / MASTERCLASS</p><h1>${c.title}</h1><p>${c.desc}</p><div class="course-meta"><span>${c.lessons} บทเรียน</span><span>${c.duration}</span><span>เรียนได้ตลอดชีพ</span></div><a href="#/checkout/${c.id}" class="button primary">รับคอร์สนี้ ฿${money(c.price)} <b>↗</b></a></div>${visual(c,'detail-visual')}</section><section class="learn-layout"><div class="learn-intro reveal"><p class="kicker">COURSE CONTENT</p><h2>เรียนทีละบท<br>ไปในจังหวะ<br>ของคุณ</h2><p>บทต่อไปจะปลดล็อกทันที เมื่อดูบทก่อนหน้าจบ เพื่อให้คุณสร้างพื้นฐานอย่างเป็นขั้นตอน</p></div><div class="lesson-list reveal">${lessons.map((l,i)=>{const unlocked=i<=done; return `<button class="lesson ${unlocked?'unlocked':''}" data-course="${c.id}" data-lesson="${i}" ${unlocked?'':'disabled'}><span class="lesson-index">0${i+1}</span><span class="lesson-title">${l.title}<small>${l.duration} นาที</small></span><span class="lesson-action">${unlocked ? (i<done ? icon('check') : icon('play')) : icon('lock')}</span></button>`}).join('')}</div></section></main>${footer()}`}
function checkout(id){const c=course(id), final=Math.max(c.price-discount,0); const qrText=`โอนเงินค่าสมัคร ${c.title}\n${BANK.bank}\nเลขบัญชี ${BANK.account}\nชื่อบัญชี ${BANK.name}\nยอดเงิน ฿${money(final)}`; const qr=`https://api.qrserver.com/v1/create-qr-code/?size=360x360&data=${encodeURIComponent(qrText)}`;return `${header()}<main class="checkout"><section class="checkout-heading"><a class="back" href="#/course/${c.id}">← กลับหน้าคอร์ส</a><p class="kicker">SECURE CHECKOUT</p><h1>เกือบถึงแล้ว<br><em>เริ่มเรียนได้เลย</em></h1></section><section class="checkout-grid"><form id="order-form" class="order-form reveal"><h2>ข้อมูลผู้เรียน</h2><label>ชื่อ<input name="firstName" autocomplete="given-name" required placeholder="ชื่อจริง" /></label><label>นามสกุล<input name="lastName" autocomplete="family-name" required placeholder="นามสกุล" /></label><label>อีเมล<input name="email" type="email" autocomplete="email" required placeholder="you@example.com" /></label><div class="payment-note"><span>✓</span><p><b>ชำระเงินด้วย QR เท่านั้น</b><br>หลังโอนเงิน กดแจ้งชำระเงินเพื่อรับสิทธิ์เรียน</p></div><button class="button primary submit" type="submit">แจ้งชำระเงินแล้ว <b>↗</b></button></form><aside class="payment-card reveal"><p class="eyebrow">ORDER SUMMARY</p><h2>${c.title}</h2><div class="price-row"><span>ราคาคอร์ส</span><span>฿${money(c.price)}</span></div><div class="price-row discount"><span>ส่วนลดเปิดตัว</span><span>− ฿${money(discount)}</span></div><div class="total"><span>ยอดชำระ</span><b>฿${money(final)}</b></div><div class="qr-box"><img src="${qr}" alt="QR สำหรับรายละเอียดการโอนเงิน"/><p>สแกนเพื่อดูรายละเอียดบัญชี</p></div><div class="bank"><b>${BANK.bank}</b><span>เลขที่บัญชี ${BANK.account}</span><span>${BANK.name}</span></div><p class="tiny">โปรดเก็บสลิปการโอนเงินไว้สำหรับยืนยันการชำระเงิน</p></aside></section></main>${footer()}`}
function about(){return `${header()}<main class="page about"><section class="page-title reveal"><p class="kicker">ABOUT SKILLRISE</p><h1>โลกเปลี่ยนไว<br>คุณก็ <em>โตทันได้</em></h1></section><section class="about-copy reveal"><p>SKILLRISE คือพื้นที่เรียนรู้สำหรับคนที่เชื่อว่าทักษะที่ใช่ เปลี่ยนชีวิตการทำงานได้ เราคัดเฉพาะสิ่งที่นำไปใช้ได้จริง และจัดให้เรียนง่ายที่สุด</p><p>ไม่มีเนื้อหาที่ยืดเยื้อ ไม่มีคำสัญญาเกินจริง มีเพียงบทเรียนที่ดี และพื้นที่ให้คุณได้ลงมือทำ</p><a class="button primary" href="#/courses">เลือกคอร์สของคุณ <b>↗</b></a></section></main>${footer()}`}
function footer(){return `<footer><a class="brand" href="#/">SKILL<span>RISE</span><i></i></a><p>เรียนรู้ทีละก้าว เติบโตในแบบของคุณ</p><span>© 2026 SKILLRISE</span></footer>`}
function offer(){return `<div class="offer" id="offer"><button class="offer-close" aria-label="ปิด">${icon('close')}</button><div class="offer-mark">SR<br><span>+</span></div><p class="kicker">WELCOME OFFER</p><h2>ส่วนลด<br><em>฿200</em></h2><p>สำหรับคอร์สแรกของคุณ<br>เฉพาะ 100 คนแรกเท่านั้น</p><div class="countdown" id="countdown">23:59:59</div><a href="#/courses" class="button lime offer-button">เลือกคอร์สเลย <b>↗</b></a><small>* ราคาพิเศษจะถูกใช้ให้อัตโนมัติ</small></div><div class="offer-backdrop" id="offer-backdrop"></div>`}
function videoModal(cId, i){const c=course(cId); return `<div class="video-modal"><div class="video-dialog"><button class="modal-close">×</button><div class="video-screen"><span>${icon('play')}</span><p>วิดีโอบทเรียน ${i+1}<br><small>ใส่ลิงก์วิดีโอของคุณในจุดนี้ได้</small></p></div><h2>บทที่ ${i+1}: ${document.querySelector(`[data-course="${cId}"][data-lesson="${i}"] .lesson-title`)?.childNodes[0]?.textContent || c.title}</h2><button class="button primary complete-lesson" data-course="${cId}" data-lesson="${i}">ดูจบแล้ว ปลดล็อกบทถัดไป <b>→</b></button></div></div>`}
function render(){ const parts=location.hash.slice(2).split('/'); let content = parts[0]==='courses'?courses():parts[0]==='course'?coursePage(parts[1]):parts[0]==='checkout'?checkout(parts[1]):parts[0]==='about'?about():home(); document.querySelector('#app').innerHTML=content + (sessionStorage.getItem('offerClosed')?'':offer()); bind(); requestAnimationFrame(()=>document.querySelectorAll('.reveal').forEach((e,i)=>setTimeout(()=>e.classList.add('in'),i*70))); }
function bind(){document.querySelector('.mobile-menu')?.addEventListener('click',()=>document.querySelector('nav').classList.toggle('open')); document.querySelector('.offer-close')?.addEventListener('click',closeOffer); document.querySelector('.offer-backdrop')?.addEventListener('click',closeOffer); document.querySelectorAll('.offer-button').forEach(x=>x.addEventListener('click',closeOffer)); document.querySelectorAll('.lesson.unlocked').forEach(b=>b.addEventListener('click',()=>{document.body.insertAdjacentHTML('beforeend',videoModal(b.dataset.course,Number(b.dataset.lesson))); document.querySelector('.modal-close').addEventListener('click',()=>document.querySelector('.video-modal').remove()); document.querySelector('.complete-lesson').addEventListener('click',finishLesson)})); document.querySelector('#order-form')?.addEventListener('submit', submitOrder);}
function closeOffer(){sessionStorage.setItem('offerClosed','1'); document.querySelector('.offer')?.classList.add('out'); document.querySelector('.offer-backdrop')?.classList.add('out'); setTimeout(()=>{document.querySelector('.offer')?.remove();document.querySelector('.offer-backdrop')?.remove()},300)}
function finishLesson(e){const {course:c,lesson}=e.currentTarget.dataset; completed[c]=Math.max(completed[c]||0,Number(lesson)+1);localStorage.setItem('skillrise-completed',JSON.stringify(completed));document.querySelector('.video-modal').remove(); render();}
function submitOrder(e){e.preventDefault();const form=new FormData(e.currentTarget);const order={...Object.fromEntries(form),course:location.hash.split('/').pop(),createdAt:new Date().toISOString()};localStorage.setItem('skillrise-last-order',JSON.stringify(order));e.currentTarget.innerHTML=`<div class="order-success"><span>✓</span><h2>รับแจ้งการชำระเงินแล้ว</h2><p>เราจะตรวจสอบยอดโอน และส่งสิทธิ์เข้าเรียนไปที่ <b>${order.email}</b> โดยเร็วที่สุด</p><a class="button primary" href="#/course/${order.course}">ไปหน้าเรียน <b>↗</b></a></div>`}
function tick(){const left=Math.max(0,endAt-Date.now()),h=String(Math.floor(left/3600000)).padStart(2,'0'),m=String(Math.floor(left%3600000/60000)).padStart(2,'0'),s=String(Math.floor(left%60000/1000)).padStart(2,'0');const el=document.querySelector('#countdown');if(el)el.textContent=`${h}:${m}:${s}`}
window.addEventListener('hashchange',()=>{window.scrollTo(0,0);render()}); setInterval(tick,1000);render();tick();
